### ISSUE TITLE
PROJECT: Quotes at the bottom

### ISSUE THREAD

**Issue by ashleyscopes** [kxx14cdu/CMP_4011A_CW1#10]
Why don't we do quotes along the bottom in the footer from visitors that are "picked out of a javascript hat" on page load.http://www.bressingham.co.uk/home.aspx is a nice example.

**Comment by kxx14cdu** [comment]
Ah yeah thats actually what I was going to message you about haha, just got home

Basically I've been worked on along other css things, a kind of better looking layout for the site CSS wise. I will upload a design of it later, the CSS is mostly done. Basically drop down menus and quotes and stuff, can still use your javascript stuff obviously and the code as its mostly CSS changes

**Comment by ashleyscopes** [comment]
okydokes
