### ISSUE TITLE
PROJECT: Rewrite main.css, mobile.css and grid.css

### ISSUE THREAD

**Issue by ashleyscopes** [kxx14cdu/CMP_4011A_CW1#11]
Make them neat, remove any redundant statements I have missed, erm...

Commenting! :-)

**Comment by ashleyscopes** [comment]
![dat-download-speed](https://cloud.githubusercontent.com/assets/14885638/10677122/6d60868a-7902-11e5-898b-be37c1839543.PNG)
Should we bother with making a printer friendly version?

**Comment by kxx14cdu** [comment]
Don’t think there is much point considering that seems to work well

From: Ashley Scopes
Reply-To: kxx14cdu/CMP_4011A_CW1
Date: Thursday, 22 October 2015 at 21:18
To: kxx14cdu/CMP_4011A_CW1
Subject: Re: [CMP_4011A_CW1] PROJECT: Rewrite main.css, mobile.css and grid.css (#11)


[dat-download-speed]<https://cloud.githubusercontent.com/assets/14885638/10677122/6d60868a-7902-11e5-898b-be37c1839543.PNG>
Should we bother with making a printer friendly version?
