### ISSUE TITLE
CSS mobile and grid issue

### ISSUE THREAD

**Issue by ashleyscopes** [kxx14cdu/CMP_4011A_CW1#6]
![issue](https://cloud.githubusercontent.com/assets/14885638/10571705/7a9051bc-7639-11e5-9c96-4bfa540358a0.png)
The mobile grid is still appearing like the desktop grid, instead of stacking as one row...

Also, if I place 3x four-column divs, the third will wrap to the next line rather than staying put on the same line. I do not understand the CSS that is causing this to happen, so I cannot adjust it.

Cheers

Ashley

**Comment by ashleyscopes** [comment]
See my commit message.

I went into grid.css and altered the line in
@media (min-width: 550px) {
	.container {
		width: 80%;
		margin-left: 3%;
	}
	.column {
		margin-left: 0%;
	}
	.column:first-child {
		margin-left: 0px;
	}
}
that reads ".container {... margin-left:3%...} to {... padding:3%...} and now the CSS works.

**Comment by kxx14cdu** [comment]
I don't remember putting in the margins in percentages haha I don't think that works so probably why it broke. Also, when doing the columns, it's also good to wrap them in a class="row" div tag. This clears the divs so that they collapse and display properly. It isn't entirely necessary but just sometimes needed :)

**Comment by ashleyscopes** [comment]
Can you show me what you mean?
On 19 Oct 2015 09:15, Alixander Roden <notifications@github.com> wrote:I don't remember putting in the margins in percentages haha I don't think that works so probably why it broke. Also, when doing the columns, it's also good to wrap them in a class="row" div tag. This clears the divs so that they collapse and display properly. It isn't entirely necessary but just sometimes needed :)

**Comment by kxx14cdu** [comment]
Basically the syntax for the grid system is:
```
<div class="container"> (Were using <section class="container"> instead usually)
     <div class="row">
          <div class="five column"></div>
          <div class="two column"></div>
          <div class="five column"></div>
     </div>
     <div class="row">
          <div class="five column"></div>
          <div class="two column"></div>
          <div class="five column"></div>
     </div>
</div>

```

You can mix and match columns sizes in rows, but each row must add up to twelve columns. You can also do like a two x six column row then a five, two and five column row.

**Comment by ashleyscopes** [comment]
I see
On 19 Oct 2015 09:37, Alixander Roden <notifications@github.com> wrote:Basically the syntax for the grid system is:

<div class="container"> (Were using <section class="container"> instead usually)
     <div class="row">
          <div class="five column"></div>
          <div class="two column"></div>
          <div class="five column"></div>
     </div>
     <div class="row">
          <div class="five column"></div>
          <div class="two column"></div>
          <div class="five column"></div>
     </div>
</div>



You can mix and match columns sizes in rows, but each row must add up to twelve columns. You can also do like a two x six column row then a five, two and five column row.
